version: "3"

services:
    workspace:
        image: node:16-bullseye
        working_dir: /workspace
        ports:
            - 3000:3000
        environment:
            - TZ=Asia/Shanghai
        volumes:
            - .:/workspace:cached
        command: >
            /bin/sh -c "yarn install &&
                        yarn dev"
        restart: unless-stopped
